In [1]:
#imports
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt

from sklearn.linear_model import LinearRegression
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import train_test_split, cross_val_score
from sklearn.metrics import r2_score
import sklearn.metrics as metrics

In [7]:
#upload data
genes = pd.read_csv('./sfari_genes.csv')

In [11]:
genes.head()

,status,gene-symbol,gene-name,ensembl-id,chromosome,genetic-category,gene-score,syndromic,number-of-reports
0,9,ABAT,4-aminobutyrate aminotransferase,ENSG00000183044,16,"Rare Single Gene Mutation, Genetic Association",3,0,6
1,9,ABCA10,"ATP-binding cassette, sub-family A (ABC1), mem...",ENSG00000154263,17,Rare Single Gene Mutation,3,0,1
2,9,ABCA13,ATP binding cassette subfamily A member 13,ENSG00000179869,7,"Rare Single Gene Mutation, Functional",3,0,6
3,9,ABCA7,"ATP-binding cassette, sub-family A (ABC1), mem...",ENSG00000064687,19,Rare Single Gene Mutation,3,0,4
4,9,ACE,angiotensin I converting enzyme,ENSG00000159640,17,"Rare Single Gene Mutation, Genetic Association",3,0,3

In [12]:
#upload data
gene_cnvs = pd.read_csv('./sfari_gene_cnvs.csv')

In [12]:
#upload data
gene_scores = pd.read_csv('./sfari_gene_scoring.csv')

,status,gene-symbol,gene-name,ensembl-id,chromosome,genetic-category,gene-score,syndromic,number-of-reports
0,9,ABAT,4-aminobutyrate aminotransferase,ENSG00000183044,16,"Rare Single Gene Mutation, Genetic Association",3,0,6
1,9,ABCA10,"ATP-binding cassette, sub-family A (ABC1), mem...",ENSG00000154263,17,Rare Single Gene Mutation,3,0,1
2,9,ABCA13,ATP binding cassette subfamily A member 13,ENSG00000179869,7,"Rare Single Gene Mutation, Functional",3,0,6
3,9,ABCA7,"ATP-binding cassette, sub-family A (ABC1), mem...",ENSG00000064687,19,Rare Single Gene Mutation,3,0,4
4,9,ACE,angiotensin I converting enzyme,ENSG00000159640,17,"Rare Single Gene Mutation, Genetic Association",3,0,3

In [13]:
#upload data
mouse_genes = pd.read_csv('./sfari_mouse_genes.csv')

,status,gene-symbol,gene-name,human-gene-score,human-syndromic,syntenic,model-species,number-of-models,has-rescue-model
0,9,ACTL6B,actin like 6B,S,1,Yes,Mus musculus,3,0
1,9,ADNP,Activity-dependent neuroprotector homeobox,1,0,No,Mus musculus,16,1
2,9,ADORA2A,Adenosine A2a receptor,3,0,Unknown,Mus musculus,2,0
3,9,AHI1,Abelson helper integration site 1,S,1,Unknown,Mus musculus,5,1
4,9,ALDH5A1,"Aldehyde Dehydrogenase 5 family, member A1",1,0,Unknown,Mus musculus,4,1

In [14]:
#upload data
mouse_gene_cnvs = pd.read_csv('./sfari_mouse_gene_cnvs.csv')

,status,cnv-locus,cnv-type,human-cnv-loci,number-of-models,has-rescue-model,model-species
0,9,m7qB5-qC,Duplication,15q11-q13,7,1,Mus musculus
1,9,m7qC,Deletion-Duplication,15q13.3,3,0,Mus musculus
2,9,m7qF3,Deletion-Duplication,16p11.2,60,1,Mus musculus
3,9,m11qB1.3-qB2,Deletion-Duplication,17p11.2,4,1,Mus musculus
4,9,m,Deletion-Duplication,3q29,0,0,Mus musculus

In [15]:
#upload data
mouse_inbred = pd.read_csv('./sfari_mouse_inbred.csv')

,id,status,strain-symbol,strain-name,model-species,number-of-models,has-rescue-model
0,1,9,BALBcByJ,BALB/cByJ,Mus musculus,24,1
1,2,9,BTBR,BTBR T+ Itpr3tf/J,Mus musculus,73,1
2,3,9,129S1SVIMJ,129S1/SvImJ,Mus musculus,1,0
3,4,9,AJ,A/J,Mus musculus,1,0
4,5,9,EL,EL/SuzSeyFrkJ,Mus musculus,3,1

In [16]:
#upload data
mouse_induced = pd.read_csv('./sfari_mouse_induced.csv')

,id,status,inducer-symbol,inducer-name,inducer-subtype,model-species,number-of-models,has-rescue-model
0,1,9,Cow milk allergen,Cow milk allergen,Biological,Mus musculus,6,1
1,2,9,ACC-INACT,Anterior cingulate cortex inactivation,Biological,Mus musculus,1,0
2,3,9,Advanced paternal age,Advanced paternal age,Biological,Mus musculus,5,0
3,4,9,As,Arsenic,Chemical,Mus musculus,1,0
4,5,9,BDE-47,"2,2',4,4'-Tetrabromodiphenyl ether",Chemical,Mus musculus,1,0

In [17]:
#upload data
mouse_rescue = pd.read_csv('./sfari_mouse_rescue.csv')

,status,model-id,model-symbol,model-type,model-species,rescue-type,rescue-agent,number-of-rescue-models,parent-model-name
0,9,M_ADNP_1_KO_HT_NAP,ADNP,Genetic,Mus musculus,Pharmaceutical,NAP,3,M_ADNP_1_KO_HT
1,9,M_ADNP_1_KO_HT_SKIP,ADNP,Genetic,Mus musculus,Pharmaceutical,SKIP,2,M_ADNP_1_KO_HT
2,9,M_ADNP_2_KO_HT_NAP,ADNP,Genetic,Mus musculus,Pharmaceutical,NAP,2,M_ADNP_2_KO_HT
3,9,M_ALDH5A1_1_KO_HM_CGP-35348,ALDH5A1,Genetic,Mus musculus,Pharmaceutical,CGP 35348,1,M_ALDH5A1_1_KO_HM
4,9,M_ALDH5A1_1_KO_HM_Vigabatrin,ALDH5A1,Genetic,Mus musculus,Pharmaceutical,Vigabatrin,1,M_ALDH5A1_1_KO_HM